"""empty message

Revision ID: 9e967fcf982f
Revises: 
Create Date: 2026-03-24 20:45:23.782784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9e967fcf982f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviceprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('screen_res', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deviceprofile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deviceprofile_device_uuid'), ['device_uuid'], unique=True)

    op.create_table('historyentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historyentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historyentry_device_uuid'), ['device_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historyentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historyentry_device_uuid'))

    op.drop_table('historyentry')
    with op.batch_alter_table('deviceprofile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deviceprofile_device_uuid'))

    op.drop_table('deviceprofile')
    # ### end Alembic commands ###
